# models.py

from odoo import models, fields


class CustomReport(models.AbstractModel):
   _name = 'report.cafe.report_template_id'

   @staticmethod
   def get_report_values(data=None):
      # Access data generated by the wizard
      start_date = data.get('start_date')
      end_date = data.get('end_date')


      report_data = {
         'start_date': start_date,
         'end_date': end_date,

      }

      return report_data
